---
driver:
  name: docker
  hostname: letsencrypt-formula.example.com

driver_config:
  use_sudo: false
  privileged: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - mkdir -p /run/sshd
      run_command: /lib/systemd/systemd
  - name: ubuntu-18.04
    driver_config:
      provision_command:
        - mkdir -p /run/sshd
      run_command: /lib/systemd/systemd
  - name: debian-9
    driver_config:
      provision_command:
        - mkdir -p /run/sshd
      run_command: /lib/systemd/systemd
  - name: centos-7
    driver_config:
      image: saltstack/centos-7-minimal
      provision_command:
        - mkdir -p /run/sshd
      run_command: /lib/systemd/systemd

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: letsencrypt
  salt_copy_filter:
    - .kitchen
    - .git

  state_top:
    base:
      "*":
        - letsencrypt.install

  dependencies:
    - name: apt
      repo: git
      source: https://github.com/saltstack-formulas/apt-formula.git

  pillars:
    top.sls:
      base:
        '*':
          - apt
          - letsencrypt
    apt.sls:
      apt:
        repositories:
          #####
          letsencrypt-backports:
            distro: stretch-backports
            url: http://deb.debian.org/debian
            comps: [main]
        preferences:
          letsencrypt-backports:
            pin: release a=stretch-backports
            priority: 640
    # epel.sls:
    #  epel:
    #    disabled: false
    letsencrypt.sls:
      letsencrypt:
        use_package: true
        config: |
          server: https://acme-staging.api.letsencrypt.org/directory
          email: saltstack-letsencrypt-formula@example.com
          authenticator: webroot
          webroot-path: /var/www/html
          agree-tos: true
          renew-by-default: true

suites:
  - name: default
    excludes:
      - centos-7
      - debian-9
    verifier:
      inspec_tests:
        - test/integration/default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - letsencrypt
        letsencrypt.sls:
          letsencrypt:
            use_package: false
            config: |
              server = https://acme-staging.api.letsencrypt.org/directory
              authenticator = standalone
              agree-tos = True
              renew-by-default = True
            domainsets:
              www:
                - letsencrypt-formula.example.com
  - name: deb
    excludes:
      - centos-7
      - ubuntu-18.04
      - ubuntu-16.04
    verifier:
      inspec_tests:
        - test/integration/deb
    provisioner:
      top.sls:
        base:
          '*':
            - apt.repositories
            - apt.preferences
            - apt.update
            - letsencrypt.install
            - letsencrypt.service
            - letsencrypt.config
      apt.sls:
        apt:
          repositories:
            #####
            letsencrypt-backports:
              distro: stretch-backports
              url: http://deb.debian.org/debian
              comps: [main]
            preferences:
              letsencrypt-backports:
                pin: release a=stretch-backports
                priority: 640

  - name: rpm
    excludes:
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    verifier:
      inspec_tests:
        - test/integration/rpm
    provisioner:
      state_top:
        base:
          '*':
            # - epel
            - letsencrypt.install
            - letsencrypt.config
