sudo: required
cache: bundler
language: ruby

services:
  - docker

env:
  matrix:
    - INSTANCE=debian-9
    - INSTANCE=centos-7
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-ubuntu-1804

before_install:
  - bundle install

script: bundle exec kitchen verify $INSTANCE
